config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :students do 
    resources :lessons
  end
  resources :instructors
  get '/', to: "application#home", as: 'home'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/chuck', to: 'lessons#lesson_with_chuck'  
  get '/:anything', to: "application#wrong_page"
  match '/auth/:provider/callback', to: 'sessions#google', via: [:get, :post]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/instructor.rb
class Instructor < ApplicationRecord
    has_many :lessons
    has_many :students, through: :lessons

    validates :name, uniqueness: true, presence: true  
end

app/models/lesson.rb
class Lesson < ApplicationRecord
    belongs_to :instructor
    belongs_to :student 

    validates :appointment_day, presence: true
    validates :level, presence: true 

    scope :beginner_level, -> {where(level: "beginner")}
    scope :intermediate_level, -> {where(level: "intermediate")}
    scope :advanced_level, -> {where(level: "advanced")}
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :lessons
    has_many :instructors, through: :lessons

    validates :username, presence: true 
    validates :email, uniqueness: true, presence: true 

    has_secure_password 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    helper_method :logged_in?
    helper_method :current_student

    def home
        render "/home"
    end

    def redirect_if_not_logged_in
        if !logged_in?
            redirect_to home_path
        end
    end 

    def wrong_page
        render "/wrong_page"
    end


    def current_student
        @student = Student.find_by_id(session[:student_id])
    end
    
    def logged_in?
        !current_student.nil?
    end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
    def index 
        @instructors = Instructor.all
        @sorted_instructors = Instructor.all.sort_by {|i| i.lessons.count} #sort_by defaults by ascending order
    end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
    before_action :redirect_if_not_logged_in
    
    def index
        @lessons = current_student.lessons
        @beginner_lessons = Lesson.beginner_level
        @intermediate_lessons = Lesson.intermediate_level
        @advanced_lessons = Lesson.advanced_level
    end

    def new
        #@lesson = Lesson.new #getting empty instance of lesson
        @lesson = current_student.lessons.build
    end

    def create
    @lesson = current_student.lessons.build(lesson_params)
        if @lesson.save
            redirect_to student_lesson_path(student_id: current_student.id, id: @lesson.id)
        else 
            render :new
        end   
    end

    def show 
    @lesson = Lesson.find(params[:id])     
    end

    def edit
        @lesson = Lesson.find(params[:id])
    end 

    def update
        @lesson = Lesson.find(params[:id])
        @lesson.update(lesson_params)
        redirect_to student_lesson_path(current_student, @lesson)
    end 

    def destroy
        @lesson = Lesson.find(params[:id])
        @lesson.destroy
        redirect_to student_lessons_path
    end 

    def lesson_with_chuck
        @lesson = current_student.lessons.build(instructor_id: 1, level: "intermediate", appointment_day: "Monday")
        @lesson.save
        redirect_to student_lessons_path(current_student)
    end


    private

    def lesson_params
        params.require(:lesson).permit(:instructor_id, :level, :appointment_day)
 end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @student = Student.find_by(email: params[:email])
    if @student && @student.authenticate(params[:password])
      session[:student_id] = @student.id
      redirect_to @student
    else
      flash[:danger] = 'Incorrect username and password'
      render :new
    end
  end

  def google
    @student = Student.find_or_create_by(email: auth["info"]["email"]) do |student|
      student.password = SecureRandom.hex(10)
      student.username = auth["info"]["username"]
      student.first_name = auth["info"]["first_name"]
      student.last_name = auth["info"]["last_name"]
    end
    if student
        session[:student_id] = student.id
        redirect_to student_path(student)
    else
      redirect_to "/"
    end
  end
 
  def destroy
    session.clear
    redirect_to "/"
  end

  private

  def auth
    request.env['omniauth.auth']
  end


end 

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    before_action :redirect_if_not_logged_in, only: [:show]

    def new
        @student = Student.new
    end 

    def create 
        student = Student.new(student_params)
        if student.save 
            session[:student_id] = student.id 
            redirect_to student_path(student) # running student.id in the backend 
        else 
            redirect_to new_student_path # back to sign up form
        end
    end 

    def show
        @student = Student.find(params[:id])
    end 

    def edit
        @student = Student.find(params[:id])
    end 

    def update
        @student = Student.find(params[:id])
        @student.update(student_params)
        redirect_to student_path
    end 

    private 

    def student_params
        params.require(:student).permit(:username, :password, :password_confirmation, :name, :email, :phone_number)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/instructors/index.html.erb
<h1> Meet our Instructors! </h1>

<% @instructors.each do |instructor| %>
    <h2> <%= instructor.name %> </h2>
    <h2> <%= instructor.bio %> </h2>
<% end %>
<br>

<h3> Most Popular Instructor: </h3>
<h5> <%= @sorted_instructors[-1].name %> </h5>

app/views/layouts/_navbar.html.erb
<% if logged_in? %>
<%= link_to 'Book lesson', new_student_lesson_path(current_student) %>
<%= link_to 'Profile', student_path(current_student) %>
<%= link_to 'Instructors', instructors_path %>
<%= link_to 'Lessons', student_lessons_path(current_student) %>
<%= link_to 'Book with Chuck', chuck_path %>
<%= link_to 'Logout', logout_path, method: :delete %>
<% else %>
<%= link_to 'Signup', new_student_path %>
<%= link_to 'Login', login_path %>
<%= link_to "Login with Google", '/auth/google_oauth2/callback', method: :post%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SkiLessons</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lessons/edit.html.erb
<%= form_with model: @lesson, url: student_lesson_path(current_student, @lesson), local: true do |f| %>
    <%= f.label :instructor %>
    <%= f.select :instructor_id, Instructor.all.collect {|i| [i.name, i.id]} %>
    
    <%= f.label :level %>
    <%= f.select :level, ["beginner", "intermediate", "advanced"] %>

   <%= f.label :appointment_day %>
   <%= f.select :appointment_day, ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", 
   "Sunday"] %>
    
   <%= f.submit "submit" %> 
   
<% end %>

app/views/lessons/index.html.erb
<h1> Your Lessons </h1>

<% if !@beginner_lessons.empty? %>
<h2><u> Here are your beginner lessons </u> </h2>
    <% @beginner_lessons.each do |lesson| %>
        <p>
        <h3> Instructor Name: <%= lesson.instructor.name %> </h3>
        <h3> Lesson Day: <%= lesson.appointment_day %> </h3>
        <h3> Level: <%= lesson.level %> </h3>
        <%= link_to "Modify Lesson", edit_student_lesson_path(current_student, lesson) %>
        <%= link_to "Cancel Lesson", student_lesson_path(current_student, lesson), method: :delete %> 
        </p>
        <br>
    <% end %>
<% end %>


<% if !@intermediate_lessons.empty? %>
<h2> <u> Here are your intermediate lessons </u> </h2>
    <% @intermediate_lessons.each do |lesson| %>
        <p>
        <h3> Instructor Name: <%= lesson.instructor.name %> </h3>
        <h3> Lesson Day: <%= lesson.appointment_day %> </h3>
        <h3> Level: <%= lesson.level %> </h3>
        <%= link_to "Modify Lesson", edit_student_lesson_path(current_student, lesson) %>
        <%= link_to "Cancel Lesson", student_lesson_path(current_student, lesson), method: :delete %>  
        </p>
        <br>
    <% end %>
<% end %>

<% if !@advanced_lessons.empty? %>
<h2> <u> Here are your advanced lessons </u> </h2>
    <% @advanced_lessons.each do |lesson| %>
        <p>
        <h3> Instructor Name: <%= lesson.instructor.name %> </h3>
        <h3> Lesson Day: <%= lesson.appointment_day %> </h3>
        <h3> Level: <%= lesson.level %> </h3>
        <%= link_to "Modify Lesson", edit_student_lesson_path(current_student, lesson) %>
        <%= link_to "Cancel Lesson", student_lesson_path(current_student, lesson), method: :delete %> 
        </p>
        <br>
    <% end %>
<% end %>

app/views/lessons/new.html.erb
<% if @lesson.errors.any? %>
    <p><% @lesson.errors.full_messages.to_sentence %></p>
<% end %>

<%= form_with model: @lesson, url: student_lessons_path, local: true do |f| %>
    <%= f.label :level %>
    <%= f.select :level, ["beginner", "intermediate", "advanced"] %>

    <%= f.label :instructor %>
    <%= f.select :instructor_id, Instructor.all.collect {|i| [i.name, i.id]} %>

   <%= f.label :appointment_day %>
   <%= f.select :appointment_day, ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", 
   "Sunday"] %>
    
   <%= f.submit "book lesson" %>

<% end %>

app/views/lessons/show.html.erb
<h1> Your Booking Confirmation </h1>
<h2> Name: <%= @lesson.student.name %> </h2>
<h2> Level: <%= @lesson.level %> </h2>
<h2> Instructor Name: <%= @lesson.instructor.name %> </h2>
<h2> Lesson Day: <%= @lesson.appointment_day %> </h2>


<%= link_to "Modify Lesson", edit_student_lesson_path(@student, @lesson) %>
<%= link_to "Cancel Lesson", student_lesson_path(@student, @lesson), method: :delete %> 

app/views/students/edit.html.erb
<%= form_with model: @student, url: student_path, local: true do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <br>
    <br>

    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %> 
    <br>x
    <br>

    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <br>

   <%= f.label :email %>
   <%= f.email_field :email %>
   <br>
   <br>

   <%= f.label :phone_number %>
   <%= f.phone_field :phone_number %>
   <br>
   <br>
    
   <%= f.submit "Confirm Changes" %>
<% end %>

app/views/students/login.html.erb
<h1> login </h1>
<%= form_with model: @student, local: true do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :password %>
    <%= f.password_field :password %>

app/views/students/new.html.erb
<h1> Please Sign Up </h1>

<%= form_with model: @student, local: true do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <br>
    <br>

    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %> 
    <br>
    <br>

    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <br>

   <%= f.label :email %>
   <%= f.email_field :email %>
   <br>
   <br>

   <%= f.label :phone_number %>
   <%= f.phone_field :phone_number %>
   <br>
   <br>

   <%= f.label :age %>
   <%= f.number_field :age %>
   <br>
   <br>
    
   <%= f.submit "Signup" %>
<% end %>

app/views/students/show.html.erb
<h1> Welcome to your profile! </h1>

<h2> Student Information </h2>
<h3> Name: <%= @student.name %> </h3>
<h3> Email: <%= @student.email %> </h3>
<h3> Phone Number: <%= @student.phone_number %> </h3>
<%= link_to "Modify Info", edit_student_path%>
<br>